global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs: 
      - targets: ['192.168.2.11:9100','192.168.2.12:9100','192.168.2.13:9100','192.168.2.14:9100','192.168.2.15:9100','192.168.2.16:9100','192.168.2.17:9100']